### ISSUE TITLE
Sub Version download

### ISSUE THREAD

**Issue by Auno94** [ShadetHeart/AoD-Downloader#1]
Die möglichkeit die Japansiche sprachausgabe runter zuladen wäre praktisch

**Comment by ShadetHeart** [comment]
Done, als temporären fix habe ich einfach ein zusätzliches Skript für die Japanische Version ins repo geladen.

**Comment by Auno94** [comment]
Funktioniert schon prima, nur bei reinen Japanischen Titeln wie z.B. anime/325 funktioniert der nicht

**Comment by ShadetHeart** [comment]
Ja, da verwendest du das normale Skript.

**Comment by Auno94** [comment]
hm.. okay, 3 mal tesen 2 mal lief es nicht. danke funktioniert jetzt. (ggf. wolte ein pytho nicht)

**Comment by ShadetHeart** [comment]
Wenn ich mal Zeit dafür habe vereine ich das ganze und verpasse dem eventuell eine Bedienoberfläche. :)
