### ISSUE TITLE
Death Note Live Action Film bricht kurz vor Downloadende ab

### ISSUE THREAD

**Issue by YugiFanGX** [ShadetHeart/AoD-Downloader#10]
```
Downloading Episode 1:
Downloaded chunk 873 of 947 (92.19%)
Merging chunks
Cleanup
Traceback (most recent call last):
  File "./download_anime_hq.py", line 170, in <module>
    download(episode_chunk0_url,episode_title,counter)
  File "./download_anime_hq.py", line 85, in download
    os.remove(filename)
FileNotFoundError: [Errno 2] No such file or directory: '873.ts'
```

**Comment by ShadetHeart** [comment]
> ```
> Downloading Episode 1:
> Downloaded chunk 873 of 947 (92.19%)
> Merging chunks
> Cleanup
> Traceback (most recent call last):
>   File "./download_anime_hq.py", line 170, in <module>
>     download(episode_chunk0_url,episode_title,counter)
>   File "./download_anime_hq.py", line 85, in download
>     os.remove(filename)
> FileNotFoundError: [Errno 2] No such file or directory: '873.ts'
> ```

Sollte nun gefixt sein, bitte einmal testen.

**Comment by YugiFanGX** [comment]
```
requests.exceptions.MissingSchema: Invalid URL 'YPE html>\n<!--[if lt IE 7]>      <html class=': No schema supplied. Perhaps you meant http://YPE html>
<!--[if lt IE 7]>      <html class=?
```
Neuer Fehler

**Comment by ShadetHeart** [comment]
Bluray ist auch 1080p aber nochmal eine deutlich erhöhte Bitrate.

**Comment by ShadetHeart** [comment]
> ```
> requests.exceptions.MissingSchema: Invalid URL 'YPE html>\n<!--[if lt IE 7]>      <html class=': No schema supplied. Perhaps you meant http://YPE html>
> <!--[if lt IE 7]>      <html class=?
> ```
> 
> Neuer Fehler. Abgesehen davon, was ist der Unterschied zwischen Bluray und Full HD?

Welche Einstellungen und URL genau?

**Comment by YugiFanGX** [comment]
Die Death Note URL.
```
[Settings]
quality = bluray
sub = no
episode_start = 1
episode_end = 9999
```

**Comment by ShadetHeart** [comment]
> > Bluray ist auch 1080p aber nochmal eine deutlich erhöhte Bitrate.
> > Also bessere Qualität?
> 
> Welche Einstellungen und URL genau?
> https://www.anime-on-demand.de/anime/307
> 
> ```
> [Settings]
> quality = bluray
> sub = no
> episode_start = 1
> episode_end = 9999
> ```

Sollte nun funktionieren.

**Comment by YugiFanGX** [comment]
Tut es dem Anschein nach nicht

**Comment by YugiFanGX** [comment]
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.anime-on-demand.delt-ie9%20lt-ie8%20lt-ie7', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4f59ffa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Comment by ShadetHeart** [comment]
> `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.anime-on-demand.delt-ie9%20lt-ie8%20lt-ie7', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4f59ffa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Der Fehler deutet darauf hin, dass du zu viele Anfragen an den Server geschickt hast und er diese aktiv blockiert.

**Comment by ShadetHeart** [comment]
Bei mir funktioniert der Download mit den oben angegebenen Einstellungen.

**Comment by ShadetHeart** [comment]
> Bei mir funktioniert der Download mit den oben angegebenen Einstellungen.

Testsystem: Windows

**Comment by YugiFanGX** [comment]
Linux

**Comment by ShadetHeart** [comment]
> Linux

Alles klar, ich werde versuchen es die Tage auf Linux zu testen und den Fehler zu finden.

**Comment by YugiFanGX** [comment]
Hoppla, Benutzer und Passwort nach dem Pull vergessen gehabt. Jetzt läuft alles wie es soll

**Comment by YugiFanGX** [comment]
Nein doch nicht. Ich wär froh, wenn du nochmal drüber gucken könntest

**Comment by ShadetHeart** [comment]
> Nein doch nicht. Ich wär froh, wenn du nochmal drüber gucken könntest

Ich kann den Fehler leider nicht reproduzieren, auf meinem Linux system läuft es auch eiwandfrei. Habe als test mal den gesamten Film mit den gleichen Einstellungen heruntergeladne.

**Comment by YugiFanGX** [comment]
Beim Raspberry Pi OS funktioniert es nicht, dafür aber am Desktop. Deswegen mach ich hier zu.

Vielleicht hilft es wenn ich die komplette Fehlermeldung poste?

```
Enter anime url: https://anime-on-demand.de/anime/278
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb59e3b10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.anime-on-demand.delt-ie9%20lt-ie8%20lt-ie7', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb59e3b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./AoD_downloader.py", line 194, in <module>
    episode_list = get_playlist(session, anime_url)
  File "./AoD_downloader.py", line 51, in get_playlist
    response = session.get(playlist_url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.anime-on-demand.delt-ie9%20lt-ie8%20lt-ie7', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb59e3b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

```
