### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by Askadelion** [ShadetHeart/AoD-Downloader#11]
Den Download ein wenig style verpassen:
![ss (2020-07-20 at 12 05 08)](https://user-images.githubusercontent.com/41443013/87926264-bb49f680-ca81-11ea-9a33-ef50253e3088.png)

![ss (2020-07-20 at 12 06 52)](https://user-images.githubusercontent.com/41443013/87926271-bd13ba00-ca81-11ea-9868-a809d1275d4a.png)

**Comment by h4llow3En** [comment]
I have done some Progressbar in #14. I have chosen to use `progress` since it has a much easier way of addressing it an a better python3 support
