### ISSUE TITLE
Both Updated Script and old Script not working (Mac)

### ISSUE THREAD

**Issue by DragonRising66** [ShadetHeart/AoD-Downloader#15]
Hey I got some issues hope you can help me sort them out 

With the newly added script it throws me Following error after I typed in the URL from the anime 
it tells me its Logged in Successfully and after that it give me this 

Traceback (most recent call last):
  File "/Users/dragonrising66/Desktop/AoD-Downloader-master/AoD_downloader.py", line 250, in <module>
    a.setPlaylist(anime_url)
  File "/Users/dragonrising66/Desktop/AoD-Downloader-master/AoD_downloader.py", line 175, in setPlaylist
    response = self._validateResponse(
  File "/Users/dragonrising66/Desktop/AoD-Downloader-master/AoD_downloader.py", line 57, in _validateResponse
    self.currentToken = soupReturn.find(
TypeError: 'NoneType' object is not subscriptable
MacBook-Pro:AoD-Downloader-master dragonrising66$ 

and with the old script it throws me after the Anime URL directly out of the Script 

i also installed the requirements.txt but no luck on my friends Windows Machine its working flawlessly

**Comment by h4llow3En** [comment]
The old script as a cookie problem so no content gets downloaded.
The new script is currently not finished and "under construction"

I develop on a Mac so I might be able to reproduce the error.

what anime-url did you use?

**Comment by h4llow3En** [comment]
@DragonRising66 I patched up the old one. so it should work fine now.

**Comment by DragonRising66** [comment]
@h4llow3En ok now its working flawlessly with the old version 

I tried with Accel World and now that you are working currently on the streamlock support :)
