### ISSUE TITLE
FFmpeg Protocol Problem

### ISSUE THREAD

**Issue by Rennerdo30** [ShadetHeart/AoD-Downloader#17]
In the old version of AoD-Downloader, an error could occur, where ffmpeg throws an unknown protocol exception.

The series to test this is Re: Zero.
Sadly I wasn't able to run the refactored version, but I wanted to create this issue, in case that this problem still exists.

The fix for this problem is pretty simple. We just need to add "file:" in font of the filename.

**Comment by h4llow3En** [comment]
The new version wraps the usage of FFmpeg in python. But thank you for this information
