### ISSUE TITLE
add cloudfront support

### ISSUE THREAD

**Issue by Auno94** [ShadetHeart/AoD-Downloader#2]
Wenn ich aktuell versuche (python 3.8 sessions 2.22.0) eine https:// anzugeben bekomme ich Folgenden Fehler

`File "download_anime_hq_jap.py", line 157, in <module>
    episode_chunklist = session.get(episode_chunklist_url)
  File "C:\Users\nphil\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\nphil\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\nphil\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 452, in prepare_request
    p.prepare(
  File "C:\Users\nphil\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\nphil\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'http/': No schema supplied. Perhaps you meant http://http/?
`

ohne http bricht der, verständlicherweise, gleich zu beginn ab

**Comment by Auno94** [comment]
hat 1 mal funktioniert, bei einem Film, klappt bei Serien nicht
Wenn ich mir in Zeile 157 die episode_chunklistz_url ausgebe ist die nur http

**Comment by Auno94** [comment]
Fehler ist in Zeile 152 (Deutsch) bzw. 153: Durch den Wechsel zu Cloudfront gibt es wohl keine Eigentliche .Chunklist mehr

**Comment by Auno94** [comment]
Mit 
` episode_chunklists_url = episode_chunklist_url.split() `
`    episode_chunklist_url = "https://cloudfront2.anime-on-demand.de"+episode_chunklists_url[6]`

konnte ich zwar die URL bekommen für die m3u8 komme aber aktuell nicht weiter,
kann auch daran liegen dass da AWS hinter den Serien ist, während die Filme noch über die alte Plattform laufen

**Comment by YugiFanGX** [comment]
Den Fehler im Hauptbeitrag kann ich bestätigen. Hast du inzwischen zu einem Fix gefunden?

**Comment by Auno94** [comment]
ne leider nicht. So gut kenn ich mich mit python nicht aus dass ich das mit AWS hinbekomme

**Comment by YugiFanGX** [comment]
Ich genauso wenig :) Aber dein Skript war schon mal ein guter Anfang. Hier mal die Überarbeitung der zweiten Zeile:

`		episode_chunklists_url = episode_chunklist_url.split()
		episode_chunklist_url = episode_url[:(episode_url.find("/index.m3u8"))] + "/" + episode_chunklists_url[4]`

Mit Einbindung meines Codes stehen in episode_chunklist_url nun die Webadressen der index_*_.ts Files. Allerdings mit den ganzen Zusatzkram des M3U8 Dateiformats: 

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:9

Ich bin gerade etwas ratlos wie man in Python Zeilen löscht, die "#" beinhalten.

Danach wären die Links freigelegt. Anschließend muss womöglich noch die Download function überarbeitet werden.

**Comment by Askadelion** [comment]
> 
> 
> Ich genauso wenig :) Aber dein Skript war schon mal ein guter Anfang. Ich hab deine zweite Zeile mal überarbeitet. Hier der komplette Code:
> 
> > episode_chunklists_url = episode_chunklist_url.split()
> > episode_chunklist_url = episode_url[:(episode_url.find("/index.m3u8"))] + "/" + episode_chunklists_url[4]`
> 
> Mit Einbindung meines Codes stehen in episode_chunklist_url nun die Webadressen der index_*_.ts Files. Allerdings mit den ganzen Zusatzkram des M3U8 Dateiformats:
> 
> > #EXTM3U
> > #EXT-X-VERSION:3
> > #EXT-X-TARGETDURATION:9
> 
> Ich bin gerade etwas ratlos wie man in Python Zeilen löscht, die "#" beinhalten.
> 
> Danach wären die Links freigelegt. Anschließend muss womöglich noch die Download function überarbeitet werden.

mit re.compile würde ich sagen von # bis leerzeichen kenn mich jetzt aber auch nich so besonders aus diese regex sachen sind für mich auch wien buch mit sieben siegeln xD

**Comment by Askadelion** [comment]
`import m3u8

def filtern(strM3u8):
	l = str(strM3u8)
	for line in l.splitlines():
		seq = line
		if seq.endswith(","):
			continue
		print (seq)

if __name__ == '__main__' :
	playlist = m3u8.load("chunklist.m3u8")
	filtern(playlist.segments)`

der ist zwar etwas improvisiert ^^" aber so lassen sich nur die medien daten aus der m3u8 anzeigen vieleicht bringts euch was

**Comment by ShadetHeart** [comment]
Sorry, ne Weile da drauf gepennt. Werde versuchen ein script für die Cloudfront Quellen zu entwerfen.

**Comment by ShadetHeart** [comment]
Sollte nun funktionieren.

**Comment by Askadelion** [comment]
downloaden tut er *jetzt 
für das cleanen des tmp ordners hast import shutil vergessen.

wenn du das:
![ss (2020-07-18 at 11 55 44)](https://user-images.githubusercontent.com/41443013/87862618-3b713e80-c952-11ea-9a19-a32f4db2b547.png)

durch das folgende ersetzt, muss mann sich nicht ständig neu einloggen ^^

![ss (2020-07-18 at 11 56 28)](https://user-images.githubusercontent.com/41443013/87862624-53e15900-c952-11ea-8544-86addc8ae77c.png)



`

**Comment by Askadelion** [comment]
Ein fehler hat das ganze noch mit Cloudfront bsp hab jetzt ne serie bei denen sind 12 Folgen Cloudfront und ab 13 ist es wieder mit streamlook natürlich funktioniert jetzt weder das eine noch das andere script da die folgen nich seperat wählbar sind ^^""

**Comment by ShadetHeart** [comment]
Hab ich mal in einzelne issues aufgeteilt

**Comment by ShadetHeart** [comment]
> Ein fehler hat das ganze noch mit Cloudfront bsp hab jetzt ne serie bei denen sind 12 Folgen Cloudfront und ab 13 ist es wieder mit streamlook natürlich funktioniert jetzt weder das eine noch das andere script da die folgen nich seperat wählbar sind ^^""

Welche Serie genau ist das?

**Comment by Askadelion** [comment]
> 
> 
> > Ein fehler hat das ganze noch mit Cloudfront bsp hab jetzt ne serie bei denen sind 12 Folgen Cloudfront und ab 13 ist es wieder mit streamlook natürlich funktioniert jetzt weder das eine noch das andere script da die folgen nich seperat wählbar sind ^^""
> 
> Welche Serie genau ist das?
No Guns Life (Sub) 
https://www.anime-on-demand.de/anime/363

**Comment by ShadetHeart** [comment]
> > > Ein fehler hat das ganze noch mit Cloudfront bsp hab jetzt ne serie bei denen sind 12 Folgen Cloudfront und ab 13 ist es wieder mit streamlook natürlich funktioniert jetzt weder das eine noch das andere script da die folgen nich seperat wählbar sind ^^""
> > 
> > 
> > Welche Serie genau ist das?
> > No Guns Life (Sub)
> > https://www.anime-on-demand.de/anime/363

Sollte mit der neuesten version nun problemlos funktionieren.
