### ISSUE TITLE
FFmpeg error (Win 10)

### ISSUE THREAD

**Issue by SpyrexDE** [ShadetHeart/AoD-Downloader#24]
Using Windows 10 and all dependencies installed I get this error while converting:
![Screenshot_1](https://user-images.githubusercontent.com/57133330/103417676-f6ea0000-4b8b-11eb-8c83-d56338ea8d90.png)

**Comment by h4llow3En** [comment]
Please try this again using the verbose option. It might be the "too many open files error" (#23)
If this is the case try `pip install --upgrade --force-reinstall git+https://github.com/ShadetHeart/AoD-Downloader.git`
I just fixed the too many open files issue

**Comment by h4llow3En** [comment]
Also if the -v Flag is not present, please update 🙃 And test it again

**Comment by SpyrexDE** [comment]
I did what you said, looks like there is a problem with the permissions of the Temp directory:
![Screenshot_1](https://user-images.githubusercontent.com/57133330/103440780-dc299100-4c48-11eb-9ac9-b4d4fb4c08f8.png)

**Comment by h4llow3En** [comment]
Seems like that.
I have no possibility to test on windows.
Might it be possible, that those tempfiles are only accessible from the application which created it?

If you have any Idea please let me know

**Comment by h4llow3En** [comment]
I tried a rather dirty fix.
Instead of using a tempfile I place the concatinated .ts file in the output folder and remove it afterwards. Not as clean as I hoped but this will probably work. @SpyrexDE would you test it for me please? (Don't forget to reinstall :) )

**Comment by SpyrexDE** [comment]
Using version 1.0.0rc4 I get the same error 😔
Even changing the Temp directory path doesn't help.

**Comment by h4llow3En** [comment]
I updated version 1.0.0rc4 it should place the .ts output now in the same directory as the output.
Quite like in the old script. It should work.
I raised the version to 1.0.0rc5. Please try again. If it still does not work, I have to find another solution

**Comment by SpyrexDE** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/57133330/103445668-9f28c300-4c77-11eb-86d4-d49470ce9117.png)

**Comment by h4llow3En** [comment]
Damned. Yes looks like it.
